### ISSUE TITLE
Commands do not wait for previous command to finish on Linux

### ISSUE THREAD

**Issue by toolbuilder** [Vehmloewff/rollup-plugin-command#1]
Thanks for this plugin! However, the commands are running in parallel. Here's the simplest Rollup config I could come up with to replicate the issue. The intent is to run `pnpm pack` and then move the '*.tgz' file somewhere else.

```javascript
import command from 'rollup-plugin-command'
const testPackageDir = '~/temp/test-package'
export default {
  input: ['test/pool_test.js'],
  output: {
    format: 'es',
    dir: testPackageDir
  },
  plugins: [
    command([
      'pnpm pack',
      `mv *.tgz ${testPackageDir}`
    ],
    { exitOnFail: true }
    )
  ]
}
```

Here's a snippet of the resulting terminal output. You can see Rollup finishes creating the package, then a `Error: Command exited with 1` which is the `mv` command failing because the pack file does not exist yet. Then you see the command prompt. Then you start seeing output from the pack operation.

```bash
created ~/temp/test-package in 154ms
Error: Command exited with 1
user prompt:~/repositories/npm/await-for-it$ npm notice 
npm notice 📦  @toolbuilder/await-for-it@1.0.1
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE             
```

I'm running on Ubuntu 18.04.04 LTS. I don't have a Windows system to try this out on - sorry.

**Comment by toolbuilder** [comment]
Experimented a bit inside the rollup.config.js file. These are the relevant lines that provide serialized shell commands.

```javascript
import spawn from 'cross-spawn'

const runCommand = (cmdString) => {
  return new Promise((resolve, reject) => {
    const child = spawn(cmdString, [], { shell: true, stdio: 'inherit' })
    child.on('exit', (code) => resolve(code))
    child.on('error', (error) => reject(error))
  })
}

const command = (userOptions = {}) => {
  return {
    name: 'command',
    async writeBundle (outputOptions, bundle) {
      await runCommand('pnpm pack')
      await runCommand('mv -v *.tgz ~/temp/test-package')
      await runCommand('pnpm -C ~/temp/test-package install')
      await runCommand('pnpm -C ~/temp/test-package test')
    }
  }
}
```

**Comment by toolbuilder** [comment]
Ah, I see the option to wait now

**Comment by Vehmloewff** [comment]
`options.wait` should be enabled by default.  Did you set it to `false`?

If not, I guess someone will need to make it so that this option works properly.

**Comment by toolbuilder** [comment]
I didn't set any options. When I look at `src/command.ts`, it looks like `options.wait` is set to false by default. That's ok, since it seems to match `writeBundle`, which runs all plugins in parallel. Of course, the docs say it defaults to `true`, so I guess something needs to change.
